import os
import json
import urllib.request
import urllib.error

title = os.environ["ISSUE_TITLE"]
body = os.environ["ISSUE_BODY"]
issue_number = os.environ["ISSUE_NUMBER"]
repo = os.environ["REPO"]
token = os.environ["GITHUB_TOKEN"]

prompt = (
    "You are a triage bot for rust-ui, a Leptos (Rust) UI component library.\n\n"
    "A new GitHub issue was opened:\n\n"
    f"Title: {title}\n\n"
    f"Body:\n{body}\n\n"
    "Write a short, friendly comment (3-5 sentences) that:\n"
    "- Acknowledges the issue and classifies it (bug, feature request, demo issue, question, etc.)\n"
    "- Suggests a next step or workaround if obvious\n\n"
    "End your comment with: *🤖 This comment was auto-generated by a triage bot.*"
)

# Call GitHub Models API (free, uses GITHUB_TOKEN)
req = urllib.request.Request(
    "https://models.inference.ai.azure.com/chat/completions",
    data=json.dumps({
        "model": "gpt-4o-mini",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 512,
    }).encode(),
    headers={
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
)
try:
    response = json.loads(urllib.request.urlopen(req).read())
    comment = response["choices"][0]["message"]["content"]
except urllib.error.HTTPError as e:
    print(f"GitHub Models API error: {e.code} {e.read().decode()}")
    raise

# Post comment to GitHub
req2 = urllib.request.Request(
    f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments",
    data=json.dumps({"body": comment}).encode(),
    headers={
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
)
urllib.request.urlopen(req2)
print("Comment posted successfully.")
